---
soprano:
  name: sarah
  attack_time: 0.1
  decay_time: 0.1
  sustain_level: 0.7
  release_time: 0.3
  muted: false
  step_size: 16
  step_count: 32
  min_note: 72
  max_note: 96
  constructor: SimpleSynth
  volume: 40
  waveshape: sine

alto:
  name: anne
  attack_time: 0.1
  decay_time: 0.1
  sustain_level: 0.7
  release_time: 0.1
  muted: false
  step_size: 16
  step_count: 32
  min_note: 67
  max_note: 91
  constructor: AMSynth
  am_frequency: 30
  am_depth: 50
  am_waveshape: 'sawtooth'
  volume: 40

tenor:
  name: trevor
  attack_time: 0.1
  decay_time: 0.1
  sustain_level: 0.7
  release_time: 0.1
  muted: false
  step_size: 16
  step_count: 32
  min_note: 60
  max_note: 84
  constructor: FMSynth
  fm_frequency: 40
  fm_depth: 80
  fm_waveshape: 'sine'
  volume: 40

bass:
  name: brian
  attack_time: 0.1
  decay_time: 0.1
  sustain_level: 0.7
  release_time: 0.1
  muted: false
  step_size: 16
  step_count: 32
  min_note: 52
  max_note: 76
  constructor: SubSynth
  bandwidth: 20,
  volume: 40

polly:
  name: polly
  attack_time: 0.1
  decay_time: 0.1
  sustain_level: 0.7
  release_time: 0.1
  muted: false
  step_size: 16
  step_count: 32
  min_note: 72
  max_note: 91
  constructor: PolySynth
  sine_level: 60
  square_level: 20
  sawtooth_level: 20
  triangle_level: 100
  volume: 40
