---
- title: Introduction
  anchor: intro
  file: '/docs/help/introduction.md'
  children:
    - title: "What is SMIFF?"
      anchor: what_is
      file: '/docs/help/introduction/what_is_smiff.md'
    - title: 'What does SMIFF do?'
      anchor: does_what
      file: '/docs/help/introduction/what_does_smiff_do.md'
    - title: "Quick-start Guide"
      anchor: quickstart
      file: '/docs/help/introduction/quick_start_guide.md'
- title: Using the Terminal
  anchor: terminal
  file: '/docs/help/terminal.md'
- title: Available Messages
  anchor: messages
  file: '/docs/help/messages.md'
  children:
    - title: Player
      anchor: messages_player
      file: '/docs/help/messages/player.md'
      children:
        - title: play
          anchor: play
          file: '/docs/help/messages/player/play.md'
        - title: stop
          anchor: stop
          file: '/docs/help/messages/player/stop.md'
        - title: show speed
          anchor: show_speed
          file: '/docs/help/messages/player/show_speed.md'
        - title: set speed
          anchor: set_speed
          file: '/docs/help/messages/player/set_speed_to_x.md'
        - title: speed up
          anchor: speed_up
          file: '/docs/help/messages/player/speed_up.md'
        - title: speed down
          anchor: speed_down
          file: '/docs/help/messages/player/speed_down.md'
    - title: Drums
      anchor: messages_drums
      file: '/docs/help/messages/drums.md'
      children:
        - title: list
          anchor: list
          file: '/docs/help/messages/drums/list.md'
        - title: show
          anchor: show
          file: '/docs/help/messages/drums/show.md'
        - title: play
          anchor: play
          file: '/docs/help/messages/drums/play.md'
        - title: do not play
          file: '/docs/help/messages/drums/do_not_play.md'
        - title: mute
          anchor: mute
          file: '/docs/help/messages/drums/mute.md'
        - title: mute all drums
          anchor: mute_all_drums
          file: '/docs/help/messages/drums/mute_all.md'
        - title: unmute
          anchor: unmute
          file: '/docs/help/messages/drums/unmute.md'
        - title: unmute all drums
          anchor: unmute_all_drums
          file: '/docs/help/messages/drums/unmute_all.md'
        - title: clear
          anchor: clear
          file: '/docs/help/messages/drums/clear.md'
    - title: Synths
      anchor: synths
      file: '/docs/help/messages/synths.md'
      children:
        - title: list
          anchor: list_synths
          file: '/docs/help/messages/synths/list.md'
        - title: describe
          anchor: describe
          file: '/docs/help/messages/synths/describe.md'
        - title: show
          anchor: show_synth
          file: '/docs/help/messages/synths/show.md'
        - title: play
          anchor: play_synth
          file: '/docs/help/messages/synths/play.md'
        - title: do not play
          anchor: do_not_play_synth
          file: '/docs/help/messages/synths/do_not_play.md'
        - title: mute
          anchor: mute_synth
          file: '/docs/help/messages/synths/mute.md'
        - title: mute all synths
          anchor: mute_all_synths
          file: '/docs/help/messages/synths/mute_all.md'
        - title: unmute
          anchor: unmute_synth
          file: '/docs/help/messages/synths/unmute.md'
        - title: unmute all synths
          anchor: unmute_all_synths
          file: '/docs/help/messages/synths/unmute_all.md'
        - title: clear
          anchor: clear_synth
          file: '/docs/help/messages/synths/clear.md'
        - title: list parameters
          anchor: list_params
          file: '/docs/help/messages/synths/list_params.md'
        - title: set parameter
          anchor: set_param
          file: '/docs/help/messages/synths/set_param.md'

