SimpleSynth:
  name: Simple
  description: >
    A simple synthesizer which produces one single tone
    which can be one of a number of wave shapes.
  parameters:
    - name: volume
      description: >
        How loudly the synth plays.
    - name: waveshape
      description: >
        The wave shape of the tone. It can be sine, square, sawtooth or triangle.
FMSynth:
  name: Frequency Modulation
  description: >
    FM synthesisers produce two sound waves,
    one is the tone you hear (called the 'carrier')
    and the other (called the 'modulator') changes the
    frequency of the carrier.
  parameters:
    - name: volume
      description: >
        How loudly the synth plays.
    - name: fm_depth
      description: >
        How much the modulator changes the frequency of the carrier.
    - name: fm_frequency
      description: >
        The frequency of the modulator, as a proportion of the pitch.
    - name: fm_waveshape
      description: >
        The wave shape of the modulator. It can be sine, square, sawtooth or triangle.
AMSynth:
  name: Amplitude Modulation
  description: >
    AM synthesisers produce two sound waves,
    one is the tone you hear (called the 'carrier')
    and teh other (called the 'modulator') changes
    the volume of the carrier. At speed, producing
    a richer tone.
  parameters:
    - name: volume
      description: >
        How loudly the synth plays.
    - name: am_depth
      description: >
        How much the modulator changes the frequency of the carrier.
    - name: am_frequency
      description: >
        The frequency of the modulator, as a proportion of the pitch.
    - name: am_waveshape
      description: >
        The wave shape of the modulator. It can be sine, square, sawtooth or triangle.
PolySynth:
  name: Polyphonic
  description: >
    Polyphonic (poly) synthesisers produce four audible waves
    at the same frequency but with different wave shapes. 
    You can adjust the level of each one. After which they 
    are normalised to the same volume, this means that you 
    are really setting the proportions of each wave shape
    will be heard.
  parameters:
    - name: volume
      description: >
        How loudly the synth plays.
    - name: sine_level
      description: >
        How much of the sine tone will be heard.
    - name: square_level
      description: >
        How much of the square tone will be heard.
    - name: sawtooth_level
      description: >
        How much of the sawtooth tone will be heard.
    - name: triangle_level
      description: >
        How much of the triangle tone will be heard.