SimpleSynth:
  name: Simple
  decription: >
    A simple synthesizer which produces one single tone
    which can be one of a number of wave shapes.
  parameters:
    - name: volume
      description: >
        How loudly the synth plays.
    - name: fm_waveshape
      description: >
        The wave shape of the tone. It can be sine, square, sawtooth or triangle.
FMSynth:
  name: Frequency Modulation
  description: >
    FM synthesisers produce two sound waves,
    one is the tone you hear (called the 'carrier')
    and the other (called the 'modulator') changes the
    frequency of the carrier.
  parameters:
    - name: volume
      description: >
        How loudly the synth plays.
    - name: fm_depth
      description: >
        How much the modulator changes the frequency of the carrier.
    - name: fm_frequency
      description: >
        The frequency of the modulator, as a proportion of the pitch.
    - name: fm_waveshape
      description: >
        The wave shape of the modulator. It can be sine, square, sawtooth or triangle.
