bpm: 
  default: 120
  tip: Beats per minute
max_bpm:
  default: 200
  tip: Maximum beats per minute
min_bpm:
  default: 60
  tip: Minimum beats per minute
pattern_version:
  default: 0
  tip: Version of the overall pattern, used to avoid unnecessary data load.
